### ISSUE TITLE
RoadRunner detection is broken

### ISSUE THREAD

**Issue by n7olkachev** [avto-dev/stacked-dumper-laravel#8]
There is no `RR_HTTP` env variable now: https://roadrunner.dev/docs/php-environment
Maybe you could use `RR_MODE` instead?

**Comment by eldario** [comment]
@n7olkachev 

**Thank you** for contacting us, sorry for the long answer.
Can you make a **PR** for this functionality?

**Comment by n7olkachev** [comment]
Done #9
